"use client";

import { Clock, Eye, Download, ExternalLink } from "lucide-react";

interface ShareData {
  content_type: string;
  content: Record<string, unknown>;
  expires_in: number;
  view_count: number;
}

const TYPE_LABELS: Record<string, string> = {
  image: "AI 生成图片", video: "AI 生成视频", speech: "AI 语音合成",
  workflow: "AI 工作流成果", image_understand: "图片理解结果", speech_to_text: "语音转文字结果",
};

export function ShareView({ data }: { data: ShareData }) {
  const { content_type, content, expires_in, view_count } = data;
  const label = TYPE_LABELS[content_type] ?? "AI 创作内容";

  const imageUrl = (content.image_url || content.input_image_url ||
    (content.results as Record<string, string> | undefined)?.image) as string | undefined;
  const videoUrl = (content.video_url ||
    (content.results as Record<string, string> | undefined)?.video) as string | undefined;
  const audioUrl = (content.audio_url ||
    (content.results as Record<string, string> | undefined)?.speech) as string | undefined;
  const text = (content.result_text || content.transcript) as string | undefined;

  function handleDownload(url: string, filename: string) {
    const a = document.createElement("a");
    a.href = url; a.download = filename; a.target = "_blank";
    document.body.appendChild(a); a.click(); a.remove();
  }

  return (
    <div className="min-h-screen bg-zinc-950 text-white flex flex-col">
      {/* Header */}
      <header className="border-b border-zinc-800 px-6 py-4 flex items-center justify-between">
        <div>
          <p className="text-xs text-zinc-500 uppercase tracking-widest">Media AI Platform</p>
          <h1 className="text-lg font-semibold mt-0.5">{label}</h1>
        </div>
        <div className="flex items-center gap-4 text-sm text-zinc-400">
          <span className="flex items-center gap-1.5">
            <Eye className="w-4 h-4" />{view_count} 次查看
          </span>
          <span className="flex items-center gap-1.5">
            <Clock className="w-4 h-4" />
            {expires_in > 0 ? `${expires_in}h 后过期` : "已过期"}
          </span>
        </div>
      </header>

      {/* Content */}
      <main className="flex-1 flex items-center justify-center p-6">
        <div className="w-full max-w-3xl space-y-6">
          {/* Image */}
          {imageUrl && (
            <div className="relative group rounded-2xl overflow-hidden border border-zinc-800 bg-zinc-900">
              <img src={imageUrl} alt={label} className="w-full object-contain max-h-[70vh]" />
              {/* Watermark */}
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent px-4 py-3">
                <p className="text-xs text-white/60">Generated by Media AI Platform</p>
              </div>
              <button
                onClick={() => handleDownload(imageUrl, "media-ai-image.png")}
                className="absolute top-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity bg-black/60 hover:bg-black/80 border border-white/20 rounded-lg px-3 py-1.5 text-xs text-white flex items-center gap-1.5"
              >
                <Download className="w-3.5 h-3.5" />下载
              </button>
            </div>
          )}

          {/* Video */}
          {videoUrl && (
            <div className="rounded-2xl overflow-hidden border border-zinc-800 bg-black">
              <video controls src={videoUrl} className="w-full max-h-[70vh]" />
              <div className="px-4 py-3 flex items-center justify-between border-t border-zinc-800">
                <p className="text-xs text-zinc-500">Generated by Media AI Platform</p>
                <a href={videoUrl} target="_blank" rel="noopener noreferrer"
                  className="flex items-center gap-1 text-xs text-zinc-400 hover:text-white transition-colors">
                  <ExternalLink className="w-3.5 h-3.5" />新窗口打开
                </a>
              </div>
            </div>
          )}

          {/* Audio */}
          {audioUrl && (
            <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
              <p className="text-sm text-zinc-400 mb-3">音频内容</p>
              <audio controls src={audioUrl} className="w-full" />
              <p className="mt-3 text-xs text-zinc-600">Generated by Media AI Platform</p>
            </div>
          )}

          {/* Text result */}
          {text && (
            <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
              <p className="text-sm text-zinc-400 mb-3">分析结果</p>
              <p className="text-zinc-200 text-sm leading-relaxed whitespace-pre-wrap">{text}</p>
              <p className="mt-4 text-xs text-zinc-600">Generated by Media AI Platform</p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
